// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatIdTgUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ChatId        int64                  `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatIdTgUser) Reset() {
	*x = ChatIdTgUser{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatIdTgUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatIdTgUser) ProtoMessage() {}

func (x *ChatIdTgUser) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatIdTgUser.ProtoReflect.Descriptor instead.
func (*ChatIdTgUser) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ChatIdTgUser) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ChatIdTgUser) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type MessageForUpdateTgUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageForUpdateTgUser) Reset() {
	*x = MessageForUpdateTgUser{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageForUpdateTgUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageForUpdateTgUser) ProtoMessage() {}

func (x *MessageForUpdateTgUser) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageForUpdateTgUser.ProtoReflect.Descriptor instead.
func (*MessageForUpdateTgUser) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *MessageForUpdateTgUser) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ParamUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamUser) Reset() {
	*x = ParamUser{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamUser) ProtoMessage() {}

func (x *ParamUser) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamUser.ProtoReflect.Descriptor instead.
func (*ParamUser) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ParamUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ParamUser) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ParamUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ChatId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatId) Reset() {
	*x = ChatId{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatId) ProtoMessage() {}

func (x *ChatId) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatId.ProtoReflect.Descriptor instead.
func (*ChatId) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ChatId) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type NewTelegramToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewTelegramToken) Reset() {
	*x = NewTelegramToken{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewTelegramToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTelegramToken) ProtoMessage() {}

func (x *NewTelegramToken) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTelegramToken.ProtoReflect.Descriptor instead.
func (*NewTelegramToken) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *NewTelegramToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TelegramToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelegramToken) Reset() {
	*x = TelegramToken{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramToken) ProtoMessage() {}

func (x *TelegramToken) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramToken.ProtoReflect.Descriptor instead.
func (*TelegramToken) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *TelegramToken) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TelegramToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x04auth\"=\n" +
	"\fChatIdTgUser\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\x03R\x06chatId\"*\n" +
	"\x16MessageForUpdateTgUser\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"G\n" +
	"\tParamUser\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\"!\n" +
	"\x06ChatId\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\"(\n" +
	"\x10NewTelegramToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"5\n" +
	"\rTelegramToken\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\a\n" +
	"\x05Empty2\xff\x01\n" +
	"\vAuthService\x12F\n" +
	"\x12UpdateChatIdTgUser\x12\x12.auth.ChatIdTgUser\x1a\x1c.auth.MessageForUpdateTgUser\x121\n" +
	"\x10GetChatIdForUser\x12\x0f.auth.ParamUser\x1a\f.auth.ChatId\x12?\n" +
	"\x10AddTelegramToken\x12\x16.auth.NewTelegramToken\x1a\x13.auth.TelegramToken\x124\n" +
	"\x10GetTelegramToken\x12\v.auth.Empty\x1a\x13.auth.TelegramTokenB5Z3https://github.com/AndreyLebedev1998/auth-grpc/authb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_auth_proto_goTypes = []any{
	(*ChatIdTgUser)(nil),           // 0: auth.ChatIdTgUser
	(*MessageForUpdateTgUser)(nil), // 1: auth.MessageForUpdateTgUser
	(*ParamUser)(nil),              // 2: auth.ParamUser
	(*ChatId)(nil),                 // 3: auth.ChatId
	(*NewTelegramToken)(nil),       // 4: auth.NewTelegramToken
	(*TelegramToken)(nil),          // 5: auth.TelegramToken
	(*Empty)(nil),                  // 6: auth.Empty
}
var file_auth_proto_depIdxs = []int32{
	0, // 0: auth.AuthService.UpdateChatIdTgUser:input_type -> auth.ChatIdTgUser
	2, // 1: auth.AuthService.GetChatIdForUser:input_type -> auth.ParamUser
	4, // 2: auth.AuthService.AddTelegramToken:input_type -> auth.NewTelegramToken
	6, // 3: auth.AuthService.GetTelegramToken:input_type -> auth.Empty
	1, // 4: auth.AuthService.UpdateChatIdTgUser:output_type -> auth.MessageForUpdateTgUser
	3, // 5: auth.AuthService.GetChatIdForUser:output_type -> auth.ChatId
	5, // 6: auth.AuthService.AddTelegramToken:output_type -> auth.TelegramToken
	5, // 7: auth.AuthService.GetTelegramToken:output_type -> auth.TelegramToken
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
