// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatIdTgUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ChatId        int64                  `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatIdTgUser) Reset() {
	*x = ChatIdTgUser{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatIdTgUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatIdTgUser) ProtoMessage() {}

func (x *ChatIdTgUser) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatIdTgUser.ProtoReflect.Descriptor instead.
func (*ChatIdTgUser) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ChatIdTgUser) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ChatIdTgUser) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type MessageForUpdateTgUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageForUpdateTgUser) Reset() {
	*x = MessageForUpdateTgUser{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageForUpdateTgUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageForUpdateTgUser) ProtoMessage() {}

func (x *MessageForUpdateTgUser) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageForUpdateTgUser.ProtoReflect.Descriptor instead.
func (*MessageForUpdateTgUser) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *MessageForUpdateTgUser) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ParamUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParamUser     int64                  `protobuf:"varint,1,opt,name=paramUser,proto3" json:"paramUser,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamUser) Reset() {
	*x = ParamUser{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamUser) ProtoMessage() {}

func (x *ParamUser) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamUser.ProtoReflect.Descriptor instead.
func (*ParamUser) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ParamUser) GetParamUser() int64 {
	if x != nil {
		return x.ParamUser
	}
	return 0
}

type ChatId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatId) Reset() {
	*x = ChatId{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatId) ProtoMessage() {}

func (x *ChatId) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatId.ProtoReflect.Descriptor instead.
func (*ChatId) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ChatId) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x04auth\"=\n" +
	"\fChatIdTgUser\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\x03R\x06chatId\"*\n" +
	"\x16MessageForUpdateTgUser\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\")\n" +
	"\tParamUser\x12\x1c\n" +
	"\tparamUser\x18\x01 \x01(\x03R\tparamUser\"!\n" +
	"\x06ChatId\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId2\x88\x01\n" +
	"\vAuthService\x12F\n" +
	"\x12UpdateChatIdTgUser\x12\x12.auth.ChatIdTgUser\x1a\x1c.auth.MessageForUpdateTgUser\x121\n" +
	"\x10GetChatIdForUser\x12\x0f.auth.ParamUser\x1a\f.auth.ChatIdB5Z3https://github.com/AndreyLebedev1998/auth-grpc/authb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_auth_proto_goTypes = []any{
	(*ChatIdTgUser)(nil),           // 0: auth.ChatIdTgUser
	(*MessageForUpdateTgUser)(nil), // 1: auth.MessageForUpdateTgUser
	(*ParamUser)(nil),              // 2: auth.ParamUser
	(*ChatId)(nil),                 // 3: auth.ChatId
}
var file_auth_proto_depIdxs = []int32{
	0, // 0: auth.AuthService.UpdateChatIdTgUser:input_type -> auth.ChatIdTgUser
	2, // 1: auth.AuthService.GetChatIdForUser:input_type -> auth.ParamUser
	1, // 2: auth.AuthService.UpdateChatIdTgUser:output_type -> auth.MessageForUpdateTgUser
	3, // 3: auth.AuthService.GetChatIdForUser:output_type -> auth.ChatId
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
