// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.20.3
// source: auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_UpdateChatIdTgUser_FullMethodName = "/auth.AuthService/UpdateChatIdTgUser"
	AuthService_GetChatIdForUser_FullMethodName   = "/auth.AuthService/GetChatIdForUser"
	AuthService_AddTelegramToken_FullMethodName   = "/auth.AuthService/AddTelegramToken"
	AuthService_GetTelegramToken_FullMethodName   = "/auth.AuthService/GetTelegramToken"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	UpdateChatIdTgUser(ctx context.Context, in *ChatIdTgUser, opts ...grpc.CallOption) (*MessageForUpdateTgUser, error)
	GetChatIdForUser(ctx context.Context, in *ParamUser, opts ...grpc.CallOption) (*ChatId, error)
	AddTelegramToken(ctx context.Context, in *NewTelegramToken, opts ...grpc.CallOption) (*TelegramToken, error)
	GetTelegramToken(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TelegramToken, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) UpdateChatIdTgUser(ctx context.Context, in *ChatIdTgUser, opts ...grpc.CallOption) (*MessageForUpdateTgUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageForUpdateTgUser)
	err := c.cc.Invoke(ctx, AuthService_UpdateChatIdTgUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetChatIdForUser(ctx context.Context, in *ParamUser, opts ...grpc.CallOption) (*ChatId, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatId)
	err := c.cc.Invoke(ctx, AuthService_GetChatIdForUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) AddTelegramToken(ctx context.Context, in *NewTelegramToken, opts ...grpc.CallOption) (*TelegramToken, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TelegramToken)
	err := c.cc.Invoke(ctx, AuthService_AddTelegramToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetTelegramToken(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TelegramToken, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TelegramToken)
	err := c.cc.Invoke(ctx, AuthService_GetTelegramToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	UpdateChatIdTgUser(context.Context, *ChatIdTgUser) (*MessageForUpdateTgUser, error)
	GetChatIdForUser(context.Context, *ParamUser) (*ChatId, error)
	AddTelegramToken(context.Context, *NewTelegramToken) (*TelegramToken, error)
	GetTelegramToken(context.Context, *Empty) (*TelegramToken, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) UpdateChatIdTgUser(context.Context, *ChatIdTgUser) (*MessageForUpdateTgUser, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateChatIdTgUser not implemented")
}
func (UnimplementedAuthServiceServer) GetChatIdForUser(context.Context, *ParamUser) (*ChatId, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatIdForUser not implemented")
}
func (UnimplementedAuthServiceServer) AddTelegramToken(context.Context, *NewTelegramToken) (*TelegramToken, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTelegramToken not implemented")
}
func (UnimplementedAuthServiceServer) GetTelegramToken(context.Context, *Empty) (*TelegramToken, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTelegramToken not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_UpdateChatIdTgUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatIdTgUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdateChatIdTgUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_UpdateChatIdTgUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdateChatIdTgUser(ctx, req.(*ChatIdTgUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetChatIdForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParamUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetChatIdForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetChatIdForUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetChatIdForUser(ctx, req.(*ParamUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_AddTelegramToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTelegramToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).AddTelegramToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_AddTelegramToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).AddTelegramToken(ctx, req.(*NewTelegramToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetTelegramToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetTelegramToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetTelegramToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetTelegramToken(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateChatIdTgUser",
			Handler:    _AuthService_UpdateChatIdTgUser_Handler,
		},
		{
			MethodName: "GetChatIdForUser",
			Handler:    _AuthService_GetChatIdForUser_Handler,
		},
		{
			MethodName: "AddTelegramToken",
			Handler:    _AuthService_AddTelegramToken_Handler,
		},
		{
			MethodName: "GetTelegramToken",
			Handler:    _AuthService_GetTelegramToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
